### ISSUE TITLE
New command class for setting interfaces up/down

### ISSUE THREAD

**Issue by pazdera** [LNST-project/lnst#10]
`lnst-ctl` should be able to turn an interface up or down during the runtime of a command sequence. This feature could be used to easily simulate networking failures in test cases.

The command could also have an option called `after` or `interval` which would be a time range, after which would the controller turn the interface off.

See the example bellow:

``` xml
<ifctl machine="peanut" iface="if2">
    <options>
       <option name="state" value="down"/>
       <option name="wait_min" value="10"/>
       <option name="wait_max" value="15"/>
    </options>
</ifctl>
```

**Comment by olichtne** [comment]
closing as not relevant anymore...
