### ISSUE TITLE
IcmpPing test may fail due to late ARP

### ISSUE THREAD

**Issue by jiriprochazka** [LNST-project/lnst#100]
If IcmpPing test is run as first test in task, it may fail, because ARP mapping may take several seconds before estabilishing.

Do we want to make some workaround or will we just count on user will handle it manually?
Possible solutions, for example: 
1) send one ping before test execution and wait a few seconds.
2) use static ARP mapping

**Comment by jtluka** [comment]
Actually we hit this today in our setup but it's not related to ARP but rather RSTP that is delaying the forwarding of packets on the switch. In the python task we wait 15 seconds after the stack is configured but this might take longer, in our case ~20 secs. This is really dependent on what's happening in the lab and switch.
