### ISSUE TITLE
should we fallback to iproute if NM does not support device type

### ISSUE THREAD

**Issue by jtluka** [LNST-project/lnst#127]
I think that for some device types like vti and vti6 this would make sense. Need to dig into this more.

**Comment by olichtne** [comment]
We already do this, as I've exaplained in issue #151. The only possible issue is with mixing NM configuration with non-NM configuration with regards to devices in slave-master relationships... If you mean something different please provide more info.

**Comment by olichtne** [comment]
closing as not relevant anymore...
