### ISSUE TITLE
devices not supported by NM but used in recipe should raise an exception

### ISSUE THREAD

**Issue by jtluka** [LNST-project/lnst#151]
There are few device types that are currently not supported by NetworkManager,
veth, vti, vti6, loopback

These devices however have implementation in NmConfigDevice.py, e.g.

```
class NmConfigDeviceLoopback(NmConfigDeviceGeneric):                            
    #Not supported by NetworkManager                                            
    @classmethod                                                                
    def is_nm_managed(cls, dev_config, if_manager):                             
        return False
```

If a user uses them on a slave with use_nm=yes, they will be somehow managed based on inheritance from NmConfigDeviceGeneric. There will be no address configuration but still the device will be brought up and down.

This is a bug IMO, and exception should be raised to notify user that the device type is not supported on NM enabled machine.

**Comment by olichtne** [comment]
Not really... these empty NmConfig* classes are there specifically for the is_nm_managed() method that returns False. During configuration the slave tries to create {Net, Nm}ConfigDevice* classes by using the NetConfigDevice method that's on the bottom of the lnst/Slave/NetConfigDevice.py file. This function calls the is_nm_managed methods and if they return False (or if NM is disabled/not running) then the configuration falls back to the NetConfigDevice* classes...

So the up/dowm behaviour you're seeing shouldn't be related to the NmConfigDeviceGeneric class at all and should be coming from the NetConfigDevice.py code. If this is not true then there really is a bug, but I'll need more info to look into it.

**Comment by olichtne** [comment]
closing as not relevant anymore...
