### ISSUE TITLE
get_driver() returns None for bonding until lnst-slave service gets restarted

### ISSUE THREAD

**Issue by jtluka** [LNST-project/lnst#153]
Hit on following setup:

RHEL7
lnst revision 7f11e806630367f76f78d61257bf172c14aaa3c6
pyroute 62791d76b024f7c0dc50e556430084902ac1e463
recipe: regression_tests/phase1/active_backup_double_bond.xml

I've added

```
print test_if1.get_driver().get_val() 
print test_if2.get_driver().get_val() 
```

and both print None

When I restart lnst-slave, both return 'bonding'

**Comment by jtluka** [comment]
Looks like this has to be a fresh install. Not able to reproduce this by simply rebooting the machine.

**Comment by olichtne** [comment]
closing as not relevant anymore...
