### ISSUE TITLE
lnst.Slave.Job.py: missing json keyword when passing argument to exec_cmd()

### ISSUE THREAD

**Issue by jtluka** [LNST-project/lnst#196]
There's a bug at following line: https://github.com/LNST-project/lnst/blob/86c1ddd2294e78d2f8482c827bafb48e3d23dfe0/lnst/Slave/Job.py#L242

The `self._what["json"]` value is passed as value of `die_on_err` argument, which makes every command running through this method return with sucess. Instead the value should be passed with the keyword, that is `exec_cmd(...json=self._what["json"])`

**Comment by olichtne** [comment]
Good catch, I guess this has been impacting us from the start that all `host.run("<shell command>")` calls always passed?

**Comment by jtluka** [comment]
Sent a patch for review, [link](https://lists.fedorahosted.org/archives/list/lnst-developers@lists.fedorahosted.org/thread/JIQRFS63XRGN2W7ECYQPBMF7HUQSGAV3/)

**Comment by jtluka** [comment]
Fixed by commit 744844916db9d3b48ec9814cf482d815be6dd872
