### ISSUE TITLE
PauseFramesHwConfigMixin does not generate description if pause_frames_dev_list is not specified

### ISSUE THREAD

**Issue by jtluka** [LNST-project/lnst#199]
Even if the `pause_frames_dev_list` property is not defined some sort of description of the mixin setting should be generated if a class inherits from it.

**Comment by jtluka** [comment]
This applies to other mixins that should define `*dev_list` property and call `BaseHWConfigMixin._configure_dev_attribute()`, e.g. `CoalescingHWConfigMixin`.

@olichtne does this make sense?

**Comment by olichtne** [comment]
Yeah, but if the list isn't defined then that configuration will never be used so there's no need to include the mixin at all.

From what I remember, we added the `CommonHWConfigMixin` collection class to only those recipes where it made sense to use all of the included configurations, so in that case each recipe should define all the `*dev_list` properties.

Or double check that it's relevant and remove the unnecessary mixins.

**Comment by jtluka** [comment]
@olichtne what if a user wants to use the mixin but forgets to define the `*dev_list` property? With the current implementation there's no message to user about improper use of the mixin.

**Comment by olichtne** [comment]
When you add the mixin it will automatically show up in the description at least in the form of "configuration skipped". The fact that the test developer forgot to add the `*dev_list` property is in fact a bug, which should be debugged and fixed.

Question is if this description of `skipped` is good enough to do that, we could theoretically make the base `*dev_list` property method throw the `NotImplementedError()` exception, however that will also mean that it will be hard to implement collaborative `super()` calls for this property.

**Comment by jtluka** [comment]
@olichtne the problem is that the *"configuration skipped"* is not printed at all due to missing `dev_list`.

**Comment by olichtne** [comment]
Ah I see, I guess in that case it would make sense to either generate "skipped for eth0" when there is a `dev_list` and in case that `dev_list` is empty just generate "skipped completely" description?

**Comment by jtluka** [comment]
@olichtne yes, that's how I'd like to see this working. ok thanks for taking a look here. I'll follow up with a patch.

**Comment by jtluka** [comment]
Fixed by commit 5e7e9d2cec26694e10953993c3e2b7d75e26ae89
