### ISSUE TITLE
Tests/Iperf.py: res_data['msg'] is assigned twice discarding the previous content

### ISSUE THREAD

**Issue by jtluka** [LNST-project/lnst#201]
https://github.com/LNST-project/lnst/blob/66f0767c32f1b07c9326c700cde82716f756731c/lnst/Tests/Iperf.py#L45

**Comment by olichtne** [comment]
Yeah, the first assignment at https://github.com/LNST-project/lnst/blob/66f0767c32f1b07c9326c700cde82716f756731c/lnst/Tests/Iperf.py#L40 can probably be safely removed. The stderr value is reported in the result, I don't think there's a need to add a message to it...
