### ISSUE TITLE
Add pkgutil-style namespace

### ISSUE THREAD

**Issue by Axonis** [LNST-project/lnst#211]
Currently using poetry install where LNST would be a dependency would result into split installation.

Resolution: 
Add to top level __init__.py
`__path__ = __import__('pkgutil').extend_path(__path__, __name__)`

Reference:

https://packaging.python.org/guides/packaging-namespace-packages/#pkgutil-style-namespace-packages

**Comment by olichtne** [comment]
resolved in https://github.com/LNST-project/lnst/pull/212
