### ISSUE TITLE
Implement a "ContainerMapper" class 

### ISSUE THREAD

**Issue by olichtne** [LNST-project/lnst#217]
Implement a Mapper class that can be a plugin replacement for the `MachineMapper` class that will run without any pools configured, only some instance parameters (e.g. what base image to use etc....) that will read the Recipe requirements and dynamically create a complete network running lnst-slave instances specifically for the purposes of the Recipe.

A prerequisite of this may be to create an image that runs lnst-slave, but maybe we can do that dynamically - pull image, run new containers, set up network, push lnst slave code into the containers and provide matched Machine objects?

**Comment by olichtne** [comment]
https://podman.io/getting-started/network#rootfull-networking could be relevant to creating the container networks.

**Comment by enhaut** [comment]
Implemented in #221 , could be closed.
@olichtne
