### ISSUE TITLE
isinstance() check in Recipe for a device type does not work

### ISSUE THREAD

**Issue by jtluka** [LNST-project/lnst#276]
I tried following code (simplified):
```
from lnst.Devices import BridgeDevice

def MyRecipe():
    m1 = HostReq()
    m1.eth0 = DeviceReq()

    def run(self):
        bridge = BridgeDevice()

        if isinstance(bridge, BridgeDevice):
            print("yes, it is a bridge device")

```

The problem seems to be:
* imported BridgeDevice is not a type but a **function** as seen in https://github.com/LNST-project/lnst/blob/master/lnst/Devices/__init__.py#L48, therefore the `isinstance()` call would report that type is expected, not a function
* the `bridge` would be a RemoteDevice, so the type is different than expected

I came up with following method defined in `RemoteDevice`:
```
    def is_device_of_type(self, other_type):
        return self._dev_cls == other_type()._dev_cls
```
and that would be used as:
```
    if bridge.is_device_type_of(BridgeDevice):
        print("yes, it is a bridge device")
```

It works but I don't like it very much. Not sure how this can be done differently.

**Comment by olichtne** [comment]
right, i'm not sure this is entirely solvable. I remember experimenting with this and the best i came up with was what i wrote down here:

https://github.com/LNST-project/lnst/blob/master/lnst/Devices/RemoteDevice.py#L204

this ensures that `isinstance` CAN work, but you need to do a different type of import for it. I believe you need to do something like this:

```python
from lnst.Devices import BridgeDevice
import lnst.Devices.BridgeDevice.BridgeDevice

def MyRecipe():
    m1 = HostReq()
    m1.eth0 = DeviceReq()

    def run(self):
        bridge = BridgeDevice()

        if isinstance(bridge, lnst.Devices.BridgeDevice.BridgeDevice):
            print("yes, it is a bridge device")
```

this technically means that you import both the replacement "factory" method as well as the original class.

maybe there's a better solution we can come up with, just adding context to how the current way/design works.

**Comment by jtluka** [comment]
> https://github.com/LNST-project/lnst/blob/master/lnst/Devices/RemoteDevice.py#L204

To be honest, I came through this multiple times when I tried to debug this, but I could not understand it. I think we should document this in more user friendly language.

```  
      if isinstance(bridge, lnst.Devices.BridgeDevice.BridgeDevice):
            print("yes, it is a bridge device")
```

The `bridge` is still a RemoteDevice, so you'd have to use `bridge._dev_cls`.

Anyway, thanks for insight.

**Comment by olichtne** [comment]
> The bridge is still a RemoteDevice, so you'd have to use bridge._dev_cls.

well that's what the https://github.com/LNST-project/lnst/blob/master/lnst/Devices/RemoteDevice.py#L210 call is for, and why https://github.com/LNST-project/lnst/blob/master/lnst/Devices/Device.py#L34 exists - `isinstance(RemoteDevice, Device)` should work to a certain degree because of that.

**Comment by jtluka** [comment]
Ok make sense now, thanks.

**Comment by jtluka** [comment]
```
from lnst.Devices import BridgeDevice
import lnst.Devices.BridgeDevice.BridgeDevice
```

This did not work. The problem was that second import statement complains that BridgeDevice is not a module.

I tried to change to
```
from lnst.Devices import BridgeDevice
from lnst.Devices.BridgeDevice import BridgeDevice
```
... that complains with:
```
    Traceback (most recent call last):
      File "/home/igyn/tmp/lnst/lnst/Controller/Controller.py", line 172, in run
        recipe.test()
      File "/home/igyn/tmp/lnst/lnst/Recipes/ENRT/BaseEnrtRecipe.py", line 169, in test
        with self._test_wide_context() as main_config:
      File "/usr/lib64/python3.10/contextlib.py", line 135, in __enter__
        return next(self.gen)
      File "/home/igyn/tmp/lnst/lnst/Recipes/ENRT/BaseEnrtRecipe.py", line 176, in _test_wide_context
        config = self.test_wide_configuration()
      File "/home/igyn/tmp/lnst/lnst/Recipes/ENRT/LinuxBridgeOverBondRecipe.py", line 77, in test_wide_configuration
        host.bond0 = BondDevice(
    TypeError: SoftDevice.__init__() missing 1 required positional argument: 'ifmanager'
```

So, I imported with a different name:
```
from lnst.Devices import BondDevice, BridgeDevice                               
from lnst.Devices.BridgeDevice import BridgeDevice as BridgeDeviceType          
from lnst.Devices.BondDevice import BondDevice as BondDeviceType                
...
isinstance(dev, BondDeviceType)
```
... this worked fine.

**Comment by olichtne** [comment]
yup, i wasn't sure about the specifics of how to import it, i just wanted to point out that you need to import the actual device class which you use for isinstance as well as the remote device wrapper method which you use for instantiation.

Anyway, I realize that this is potentially a suboptimal solution, and we can have a discussion about how to design this better or fix it. Just wanted to provide the context that I did in fact account for this when implementing lnst-next and this was the best reasonable compromise that I was able to come up with back then.

**Comment by jtluka** [comment]
> yup, i wasn't sure about the specifics of how to import it, i just wanted to point out that you need to import the actual device class which you use for isinstance as well as the remote device wrapper method which you use for instantiation.
> 
> Anyway, I realize that this is potentially a suboptimal solution, and we can have a discussion about how to design this better or fix it. Just wanted to provide the context that I did in fact account for this when implementing lnst-next and this was the best reasonable compromise that I was able to come up with back then.

And thanks for that! I think it would be ok just to document this better. I'm fine with this solution. But sure, we can discuss this, but I think it's a low priority for now.
