### ISSUE TITLE
create an API for the switchdev VFs

### ISSUE THREAD

**Issue by jtluka** [LNST-project/lnst#345]
We have some tests that are testing VFs in https://github.com/LNST-project/lnst/blob/be9f9a0462b5192382aaceb8f5bb338a4ca03ae8/lnst/Recipes/ENRT/BaseSRIOVNetnsTcRecipe.py#L111

The code for creating the VFs can be made into an API, so that we can interact with the VFs as ordinary `Device`s.

The overall idea I currently have is:
```
host1.eth0 = DeviceReq()

sd = SwitchDevice(host1.eth0) # turns the device into 'mode switchdev', otherwise is just a Device
vf_rep_pairs = sd.create_vfs(cnt=2) # does echo $cnt > /sys/class/net/.../sriov_numvfs, returns list of (vf, vf_representor) pairs

vf_rep_pair = vf_rep_pairs[0]

type(vf_rep_pair.vf)
Device

type(vf_rep_pair.vf_rep)
Device

# move vf to netns
host1.newns = NetNamespace("lnst")
host1.newns.vf = vf_rep_pair.vf
```

**Comment by Axonis** [comment]
Makes sense, I had similar idea but wanted to go even more abstract, where we would also have e.g. SRIOVManager, that would be able to create TC rules above VF/VF-Repr/PF devices. 

Also is Device class sufficient for this use case?

**Comment by jtluka** [comment]
For all of this to work we need to modify the InterfaceManager to handle the netlink messages related to VFs.

Here's the analysis of the netlink msgs when 2 vf devices are created:
* for vf device, the message contains:
```
    1st message                                                                 
        ('IFLA_PHYS_PORT_NAME', 'pf0vf0'),                                      
        ('IFLA_PHYS_SWITCH_ID', '10:f7:d5:fe:ff:1a:3d:e4'),                     
        ('IFLA_PARENT_DEV_BUS_NAME', 'pci')                                     
        ('IFLA_PARENT_DEV_NAME', '0000:01:00.0') same as PF device              
                                                                                
    2nd message                                                                 
        ('IFLA_PHYS_PORT_NAME', 'pf0vf0'),                                      
        ('IFLA_PROP_LIST', {'attrs': [('IFLA_ALT_IFNAME', 'enp1s0f0npf0vf0')]}, 32768),
        ('IFLA_PARENT_DEV_NAME', '0000:01:00.0'),                               
                                                                                
    2nd message for 2nd vf                                                      
        ('IFLA_PHYS_PORT_NAME', 'pf0vf1'),                                      
        ('IFLA_PROP_LIST', {'attrs': [('IFLA_ALT_IFNAME', 'enp1s0f0npf0vf1')]}, 32768),
        ('IFLA_PARENT_DEV_NAME', '0000:01:00.0'),                               


```
* for vf representor devices following are generated:
```
    1st message                                                                 
    ('IFLA_PARENT_DEV_BUS_NAME', 'pci')                                         
    ('IFLA_PARENT_DEV_NAME', '0000:01:02.0'), different PCI device              
                                                                                
    2nd message                                                                 
    ('IFLA_PROP_LIST', {'attrs': [('IFLA_ALT_IFNAME', 'enp1s0f0v0')]}, 32768),  
                                                                                
    2nd message for 2nd vf_rep                                                  
    ('IFLA_PROP_LIST', {'attrs': [('IFLA_ALT_IFNAME', 'enp1s0f0v1')]}, 32768),  
```

The linkage between PF/VF/VF_REP device is:

```
PF.bus_info("pci buss address") == VF.msg['IFLA_PARENT_DEV_NAME']
VF.IFLA_PHYS_PORT_NAME ~= VF_REP.IFLA_ALT_IFNAME # this will need a bit of parsing, pf0vf0 ~= enp1s0f0v0, but the device name is consistent across various drivers
```

**Comment by jtluka** [comment]
> Makes sense, I had similar idea but wanted to go even more abstract, where we would also have e.g. SRIOVManager, that would be able to create TC rules above VF/VF-Repr/PF devices.
> 
> Also is Device class sufficient for this use case?

I think so, let's see if I encounter any issues.

**Comment by jtluka** [comment]
> Makes sense, I had similar idea but wanted to go even more abstract, where we would also have e.g. SRIOVManager, that would be able to create TC rules above VF/VF-Repr/PF devices.

I think that can be an abstraction over the abstraction I proposed. I f we agree on this proposal I'll also take a look how this would work for the filter rules.

**Comment by olichtne** [comment]
> For all of this to work we need to modify the InterfaceManager to handle the netlink messages related to VFs.

well... you started with ` host.run(f"devlink dev eswitch set pci/{host.eth0.bus_info} mode switchdev") ` ... isn't this more about devlink messages instead of netlink messages?

**Comment by jtluka** [comment]
> > For all of this to work we need to modify the InterfaceManager to handle the netlink messages related to VFs.
> 
> well... you started with `host.run(f"devlink dev eswitch set pci/{host.eth0.bus_info} mode switchdev")` ... isn't this more about devlink messages instead of netlink messages?

There are no devlink messages in that case, I've monitored the devlink, unfortunately, there's no messages sent.

**Comment by jtluka** [comment]
> > > For all of this to work we need to modify the InterfaceManager to handle the netlink messages related to VFs.
> > 
> > 
> > well... you started with `host.run(f"devlink dev eswitch set pci/{host.eth0.bus_info} mode switchdev")` ... isn't this more about devlink messages instead of netlink messages?
> 
> There are no devlink messages in that case, I've monitored the devlink, unfortunately, there's no messages sent.

Besides the VFs that need to be created differently than through devlink API, your comment makes sense and most likely we should use the pyroute'2 devlink API for setting the switchdev mode of the device. I'll check this.

**Comment by jtluka** [comment]
Draft version is available in https://github.com/jtluka/lnst/tree/switchdev-abstraction
