### ISSUE TITLE
lnst-agent crashes on controller KeyboardInterrupt during Iperf

### ISSUE THREAD

**Issue by Kuba314** [LNST-project/lnst#354]
Running a standard `SimpleNetworkRecipe`, waiting until `IperfClient` and `IperfServer` are both running, then sending `SIGINT` to controller (or just hitting `^C`) crashes both agents with the following exception:
```
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/lnst-MdZhQDa5-py3.11/bin/lnst-agent", line 6, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/lnst/lnst/Agent/__main__.py", line 45, in main
    agent.run()
  File "/root/lnst/lnst/Agent/Agent.py", line 1000, in run
    self._process_msg(msg[1])
  File "/root/lnst/lnst/Agent/Agent.py", line 1065, in _process_msg
    job.join()
    ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'join'
```

**Comment by jtluka** [comment]
I think this could be solved by moving the `join()` and `set_finished()` calls to `JobContext` class, and imo it makes sense have all jobs related tasks within the JobContext. The Agent'would only forward the message to Controller.

**Comment by jtluka** [comment]
> I think this could be solved by moving the `join()` and `set_finished()` calls to `JobContext` class, and imo it makes sense have all jobs related tasks within the JobContext. The Agent'would only forward the message to Controller.

That would mean that we'll have to call `job.join()` explicitly also in `kill_job()` and probably in other places, too. Not sure.

**Comment by Kuba314** [comment]
So any time someone would call `job.kill()`, they'd also have to call `job.join()` and `job.set_finished()`?

What if we just didn't clear the job dict in `JobContext.cleanup()` and maybe instead introduced `JobContext.pop_job()`, which would be something similar to `JobContext.get_job()`, but would also delete the job from the dict? We could then call this method in the `"job_finished"` handler instead of `JobContext.get_job()`.

WDYT? @jtluka @olichtne

**Comment by olichtne** [comment]
i'll have to try to reproduce this to inspect the state before i can be sure on how to solve this. i'll try to do that this week.
