### ISSUE TITLE
Make buffers and other constants configurable

### ISSUE THREAD

**Issue by pazdera** [LNST-project/lnst#48]
There is a number of things that are currently hard-coded, that we could easily make configurable through our configuration files. These include for instance
- [Copy to machine buffer](https://github.com/jpirko/lnst/blob/master/lnst/Controller/Machine.py#L282)
- [Copy from machine buffer](https://github.com/jpirko/lnst/blob/master/lnst/Controller/Machine.py#L299)
- [Default socket timeout](https://github.com/jpirko/lnst/blob/master/lnst/Controller/Machine.py#L33)

and many more.

**Comment by olichtne** [comment]
closing as not relevant anymore...
